//
// automatically generated by spin2cpp on Tue Nov  6 19:00:20 2012
// spin2cpp --elf -o blink.elf -O -mfcache blink.spin 
//

#ifndef blinkSpin_Class_Defined__
#define blinkSpin_Class_Defined__

#include <stdint.h>

class blinkSpin {
public:
  static const int _clkmode = 1032;
  static const int _xinfreq = 5000000;
  int32_t	Ledonoff(void);
private:
};

#endif
